### ISSUE TITLE
docker-compose up failing 

### ISSUE THREAD

**Issue by suniilsync** [hbokh/docker-jira-postgresql#6]
HI, 

When I run the 'docker-compose up' command its failing due to the following error, just i am wondering am I missing anything

[devtools@iso-buildbox docker-jira-postgresql]$ docker-compose up
Pulling jira (hbokh/docker-jira-postgresql:latest)...
ERROR: repository hbokh/docker-jira-postgresql not found: does not exist or no pull access

**Comment by hbokh** [comment]
The docker image at Docker Hub was deleted by me months ago, resulting in this error (indeed):

```txt
Pulling jira (hbokh/docker-jira-postgresql:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]
```

I have build the image based on rather old code, e.g. `phusion/baseimage / 0.9.18 / 2 years ago`so take care.
It's also pretty big: over 1.5GB.

As for now I'm planning on retiring this repo, since I have no (personal) use for this anymore.

**Comment by suniilsync** [comment]
ok, thanks
